name: Cache playwright browsers

outputs:
  cache-hit:
    description: 'Whether the cache is hit.'
    value: ${{ steps.cache-playwright-browsers.outputs.cache-hit }}
  playwright-version:
    description: 'The Playwright version.'
    value: ${{ steps.playwright-version.outputs.version }}

runs:
  using: 'composite'

  steps:
    - name: Resolve Playwright Version
      id: playwright-version
      shell: bash
      run: |
        version=$(node -p 'require("@playwright/test/package.json").version')
        if [ -z "$version" ]; then
          echo "Failed to resolve Playwright version."
          exit 1
        fi
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Cache Playwright Browsers
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: '~/.cache/ms-playwright'
        key: ${{ runner.os }}-playwright-browsers-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-playwright-browsers-

    - name: Install Browsers
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps --only-shell
    # Some WebKit dependencies cannot be cached.
    # See https://github.com/microsoft/playwright/issues/30538
    - name: Install WebKit dependencies
      shell: bash
      run: npx playwright install-deps webkit
