name: Deploy Pages

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          # The name of the artifact needs to be the same as the name previously uploaded.
          name: build-artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: './'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build markdown
        uses: actions/jekyll-build-pages@v1
        with:
          source: './'
          destination: './output'
          verbose: true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 60_000
